x-dlt-env: &dlt-env
  DESTINATION__FILESYSTEM__BUCKET_URL: "s3://flight-dlt-bucket"
  RUNTIME__LOG_LEVEL: "INFO"
  DESTINATION__FILESYSTEM__CREDENTIALS__AWS_ACCESS_KEY_ID: "admin"
  DESTINATION__FILESYSTEM__CREDENTIALS__AWS_SECRET_ACCESS_KEY: "abc123abc123!"
  DESTINATION__FILESYSTEM__CREDENTIALS__ENDPOINT_URL: "http://rustfs-1:9000"
  DESTINATION__FILESYSTEM__CREDENTIALS__REGION_NAME: "us-east-1"

services:
  airflow-apiserver:
    environment:
      <<: *dlt-env
  airflow-dag-processor:
    environment:
      <<: *dlt-env
  airflow-scheduler:
    environment:
      <<: *dlt-env
  airflow-init:
    environment:
      <<: *dlt-env